# Website settings
title: HappySmile
description: HappySmile's blog
keywords: HappySmile,blog,github,Pwn
baseurl: "" # set to "" for site root ("/")
url: https://HappySmile0725.github.io
img_path: /static/assets/img/blog  # url should be '/static/assets/img/blog' at site root

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: HappySmile  # Be used at blog posts' author.
  avatar: /static/assets/img/landing/avatar.png
  github_username: HappySmile0725
  linkedin_id: happysmile0725
  Instagram_username: 2utda
  email: h4qqy5mi1e@gmail.com
  desc: CAT-Security Pwnable HappySmile  # Describe yourself.

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

